name: Deploy Production Theme

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dev-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Get Latest code
      uses: actions/checkout@v2

    - name: Use Node 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Build Theme
      working-directory: ./wp-content/themes/paceaux3
      run: |
        npm ci
        npm run styles:build

    - name: Upload the files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{secrets.SITE_SERVER}}
        username: ${{secrets.SITE_USERNAME}}
        password: ${{secrets.SITE_PASS}}
        local-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/** 
          **/src/**
          .stylelintrc.json
          .eslintrc.json
          .gitignore
          package.json
          package-lock.json
          postcss.config.js